#!/bin/bash

if [ -z $1 ]; then
    echo "[X] A program is required to be reverse!"
    echo "EX: re /bin/ls"
    exit 0
fi

if [ ! -f $1 ]; then
    echo "[X] Can't debug a file that doesn't exist!"
    exit 0
fi

echo "[*] Connect at http://192.168.4.1:9090"
r2 -c=H -e http.bind=0.0.0.0 -d $1 > /dev/null 2>&1
echo "[X] Exiting."
